import test from"node:test";import assert from"node:assert/strict";import{generateKeyPairSync,sign}from"node:crypto";import{makeOffer,encodeFrame}from"@flop-labs/tclk";import{guardedSign,replayTranscript,runLab,settlementRefCompatibility,tclkCommitment,validatePosition,verifyTechnocoreRecord,type TransportRecord}from"../src/index.js";
const A="123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz";function b58(b:Buffer){let n=BigInt("0x"+b.toString("hex")),s="";while(n){s=A[Number(n%58n)]+s;n/=58n;}for(const x of b){if(x)break;s="1"+s;}return s;}
function signed(text:string,room="room"):TransportRecord{const kp=generateKeyPairSync("ed25519"),raw=(kp.publicKey.export({format:"der",type:"spki"})as Buffer).subarray(-32),did="did:key:z"+b58(Buffer.concat([Buffer.from([0xed,1]),raw])),nonce=7;const sig=sign(null,Buffer.from(`${room}|${nonce}|${text}`),kp.privateKey).toString("base64url");return{room,generation:3,seq:1,ts:"2026-09-07T00:00:00Z",from:did,text,nonce,sig};}
function signedOffer():TransportRecord{const kp=generateKeyPairSync("ed25519"),raw=(kp.publicKey.export({format:"der",type:"spki"})as Buffer).subarray(-32),did="did:key:z"+b58(Buffer.concat([Buffer.from([0xed,1]),raw])),room="room",nonce=7;const offer=makeOffer({from:did,role:"payer",amount:"1",asset:"FLOP",lock:"hash",rails:["paper"],claimByMs:2000,refundAfterMs:3000,expiresMs:1000,nonce:"0011223344556677"}),text=encodeFrame(offer),sig=sign(null,Buffer.from(`${room}|${nonce}|${text}`),kp.privateKey).toString("base64url");return{room,generation:3,seq:1,ts:"2026-09-07T00:00:00Z",from:did,text,nonce,sig};}
test("official release vectors pass",async()=>{const r=await runLab();assert.equal(r.summary.fail,0);assert.ok(r.summary.pass>=8);});
test("Technocore signature binds room, nonce and exact text",()=>{const r=signed("hello");assert.equal(verifyTechnocoreRecord(r),true);assert.equal(verifyTechnocoreRecord({...r,room:"other"}),false);assert.equal(verifyTechnocoreRecord({...r,text:"altered"}),false);assert.equal(validatePosition("room",3,1),"room/3/1");});
test("unsigned or mismatched transport cannot become TCLK commitment",()=>{const seed=signed("hello");assert.throws(()=>tclkCommitment(seed),/UNSIGNED|tclk/);const offer=makeOffer({from:seed.from,role:"payer",amount:"1",asset:"FLOP",lock:"hash",rails:["paper"],claimByMs:2000,refundAfterMs:3000,expiresMs:1000,nonce:"0011223344556677"});const r=signed(encodeFrame(offer));assert.throws(()=>tclkCommitment(r),/MISMATCH/);assert.throws(()=>tclkCommitment({...r,sig:undefined}),/UNSIGNED/);});
test("signing guard blocks malformed and noncanonical before signer",async()=>{const s={calls:0,async sign(){this.calls++;return"x";}};await assert.rejects(()=>guardedSign({domain:"wrong"},s));await assert.rejects(()=>guardedSign({domain:"FLOP_ROUTER_SESSION_V1",kind:"session",payload:{b:1,a:2},canonicalPayload:'{"b":1,"a":2}'},s));assert.equal(s.calls,0);});
test("transport incompatibility does not mutate refs",()=>{assert.equal(settlementRefCompatibility("a\tb").status,"RAIL_REF_TRANSPORT_INCOMPATIBLE");assert.equal(settlementRefCompatibility("safe-ref").status,"COMPATIBLE");});
test("historical replay uses venue timestamps and rejects decreasing time",()=>{const first=signedOffer();assert.doesNotThrow(()=>replayTranscript([first]));assert.throws(()=>replayTranscript([first,{...first,seq:2,ts:"2026-09-06T23:59:59Z"}]),/INVALID_HISTORICAL_TIME/);});
