import test from"node:test";import assert from"node:assert/strict";import{generateKeyPairSync,sign}from"node:crypto";import{canonicalJson,decodeFrame,encodeFrame,makeAccept,makeOffer,tryDecodeFrame}from"@flop-labs/tclk";import{guardedSign,normativeContractId,normativeOfferId,replayTranscript,runLab,settlementRefCompatibility,tclkCommitment,transportRepresentable,validatePosition,verifyTechnocoreRecord,type TransportRecord}from"../src/index.js";
const A="123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz";function b58(b:Buffer){let n=BigInt("0x"+b.toString("hex")),s="";while(n){s=A[Number(n%58n)]+s;n/=58n;}for(const x of b){if(x)break;s="1"+s;}return s;}
function signed(text:string,room="room"):TransportRecord{const kp=generateKeyPairSync("ed25519"),raw=(kp.publicKey.export({format:"der",type:"spki"})as Buffer).subarray(-32),did="did:key:z"+b58(Buffer.concat([Buffer.from([0xed,1]),raw])),nonce=7;const sig=sign(null,Buffer.from(`${room}|${nonce}|${text}`),kp.privateKey).toString("base64url");return{room,generation:3,seq:1,ts:"2026-09-07T00:00:00Z",from:did,text,nonce,sig};}
function signedOffer():TransportRecord{const kp=generateKeyPairSync("ed25519"),raw=(kp.publicKey.export({format:"der",type:"spki"})as Buffer).subarray(-32),did="did:key:z"+b58(Buffer.concat([Buffer.from([0xed,1]),raw])),room="room",nonce=7;const offer=makeOffer({from:did,role:"payer",amount:"1",asset:"FLOP",lock:"hash",rails:["paper"],claimByMs:2000,refundAfterMs:3000,expiresMs:1000,nonce:"0011223344556677"}),text=encodeFrame(offer),sig=sign(null,Buffer.from(`${room}|${nonce}|${text}`),kp.privateKey).toString("base64url");return{room,generation:3,seq:1,ts:"2026-09-07T00:00:00Z",from:did,text,nonce,sig};}
test("official release vectors pass and lanes remain distinct",async()=>{const r=await runLab();assert.equal(r.summary.fail,0);assert.ok(r.summary.pass>=8);assert.equal(r.lanes.RELEASE_CONFORMANCE,"ACTIVE");assert.equal(r.lanes.UPSTREAM_CONFORMANCE,"MANIFEST_ONLY");assert.equal(r.lanes.LIVE_CONFORMANCE,"PUBLIC_RUNTIME_UNAVAILABLE");assert.equal(r.cases.find(x=>x.id==="flop.wire-closure-e51")?.status,"SKIP");});
test("Technocore signature binds room, nonce and exact text",()=>{const r=signed("hello");assert.equal(verifyTechnocoreRecord(r),true);assert.equal(verifyTechnocoreRecord({...r,room:"other"}),false);assert.equal(verifyTechnocoreRecord({...r,text:"altered"}),false);assert.equal(validatePosition("room",3,1),"room/3/1");});
test("unsigned or mismatched transport cannot become TCLK commitment",()=>{const seed=signed("hello");assert.throws(()=>tclkCommitment(seed),/UNSIGNED|tclk/);const offer=makeOffer({from:seed.from,role:"payer",amount:"1",asset:"FLOP",lock:"hash",rails:["paper"],claimByMs:2000,refundAfterMs:3000,expiresMs:1000,nonce:"0011223344556677"});const r=signed(encodeFrame(offer));assert.throws(()=>tclkCommitment(r),/MISMATCH/);assert.throws(()=>tclkCommitment({...r,sig:undefined}),/UNSIGNED/);});
test("signing guard blocks malformed and noncanonical before signer",async()=>{const s={calls:0,async sign(){this.calls++;return"x";}};await assert.rejects(()=>guardedSign({domain:"wrong"},s));await assert.rejects(()=>guardedSign({domain:"FLOP_ROUTER_SESSION_V1",kind:"session",payload:{b:1,a:2},canonicalPayload:'{"b":1,"a":2}'},s));assert.equal(s.calls,0);});
test("transport incompatibility does not mutate refs",()=>{assert.equal(settlementRefCompatibility("a\tb").status,"RAIL_REF_TRANSPORT_INCOMPATIBLE");assert.equal(settlementRefCompatibility("safe-ref").status,"COMPATIBLE");});
test("historical replay uses venue timestamps and rejects decreasing time",()=>{const first=signedOffer();assert.doesNotThrow(()=>replayTranscript([first]));assert.throws(()=>replayTranscript([first,{...first,seq:2,ts:"2026-09-06T23:59:59Z"}]),/INVALID_HISTORICAL_TIME/);});
test("TCLK canonicalization covers Unicode, controls, safe integers and structural rejection",()=>{const fields={from:"did:key:z6Mkffffffffffffffffffffffffffffffffffffffffffff",role:"payer" as const,amount:"1",asset:"FLOP",lock:"hash" as const,rails:["paper"],claimByMs:2000,refundAfterMs:3000,expiresMs:1000,job:{proto:"a2a",id:"café"},nonce:"0011223344556677"};const offer=makeOffer(fields);const encoded=encodeFrame(offer);assert.match(encoded,/\\u00e9/);assert.deepEqual(decodeFrame(encoded),offer);assert.equal(transportRepresentable("bad\u0000text"),false);assert.equal(canonicalJson({n:Number.MAX_SAFE_INTEGER}),`{"n":${Number.MAX_SAFE_INTEGER}}`);assert.throws(()=>makeOffer({...fields,claimByMs:Number.MAX_SAFE_INTEGER+1}));const raw=JSON.parse(encoded.slice(6));raw.extra=true;assert.equal(tryDecodeFrame(`tclk1 ${canonicalJson(raw)}`),null);delete raw.extra;delete raw.amount;assert.equal(tryDecodeFrame(`tclk1 ${canonicalJson(raw)}`),null);});
test("normative ID workaround ignores structurally wider runtime objects",()=>{const offer=makeOffer({from:"did:key:z6Mkffffffffffffffffffffffffffffffffffffffffffff",role:"payer",amount:"1",asset:"FLOP",lock:"hash",rails:["paper"],claimByMs:2000,refundAfterMs:3000,expiresMs:1000,nonce:"0011223344556677"});const accept=makeAccept(offer,{from:"did:key:z6Mkgggggggggggggggggggggggggggggggggggggggggggg",statement:"0x"+"11".repeat(32),nonce:"8899aabbccddeeff"});const{id,...offerFields}=offer;const{contract,type,...acceptCore}=accept;assert.equal(normativeOfferId({...offerFields,transportOnly:{room:"r"}}),id);assert.equal(normativeContractId({...offer,transportOnly:{seq:1}},{...acceptCore,transportOnly:true}),contract);});
test("Technocore rejects malformed signatures, wrong DIDs and invalid positions",()=>{const r=signed("hello");assert.equal(verifyTechnocoreRecord({...r,sig:"not-a-signature"}),false);assert.equal(verifyTechnocoreRecord({...r,from:"did:key:z6Mkinvalid"}),false);assert.throws(()=>validatePosition("room",Number.MAX_SAFE_INTEGER+1,1));assert.throws(()=>validatePosition("room",1,Number.MAX_SAFE_INTEGER+1));});
test("transcript positions are generation-aware and monotonic",()=>{const first=signedOffer();assert.throws(()=>replayTranscript([first,{...first,seq:1}]),/NON_MONOTONIC_POSITION/);assert.throws(()=>replayTranscript([{...first,generation:4},{...first,generation:3,seq:2}]),/NON_MONOTONIC_POSITION/);});
