import{readFileSync}from"node:fs";import{pathToFileURL}from"node:url";import{decodeFrame,encodeFrame,makeAccept,makeOffer,tryDecodeFrame}from"@flop-labs/tclk";import{guardedSign}from"./signing.js";import{settlementRefCompatibility}from"./boundary.js";import{validatePosition}from"./technocore.js";import type{CaseResult,NormativeStatus}from"./types.js";
import{normativeContractId,normativeOfferId}from"./protocol-ids.js";
const run=async(id:string,suite:string,normativeStatus:NormativeStatus,fn:()=>unknown|Promise<unknown>):Promise<CaseResult>=>{const s=performance.now();try{const details=await fn();return{id,suite,status:"PASS",normativeStatus,durationMs:Math.round(performance.now()-s),details:typeof details==="object"?details as Record<string,unknown>:undefined};}catch(e){return{id,suite,status:"FAIL",normativeStatus,durationMs:Math.round(performance.now()-s),details:{error:e instanceof Error?e.message:"failed"}};}};
function mustThrow(fn:()=>unknown){let threw=false;try{fn();}catch{threw=true;}if(!threw)throw new Error("EXPECTED_REJECTION");}
export async function coreSuites(){const v=JSON.parse(readFileSync(new URL("../conformance/fixtures/tclk-v0.1.0-vectors.json",import.meta.url),"utf8"));const offer=makeOffer({from:v.payerDid,role:"payer",amount:"1000000",asset:"FLOP",lock:"hash",rails:["flop-htlc","x402"],claimByMs:1756703600000,refundAfterMs:1756707200000,expiresMs:1756700600000,job:{proto:"a2a",id:"task-3f",context:"ctx-1"},nonce:"9f2c81d04c9e1f7a"});const accept=makeAccept(offer,{from:v.payeeDid,statement:"0x"+"ab".repeat(32),nonce:"0011223344556677"});return Promise.all([
run("tclk.offer-vector","tclk","RELEASE_NORMATIVE",()=>{if(offer.id!==v.offerId)throw new Error("OFFER_ID_DIVERGENCE");return{offerId:offer.id}}),run("tclk.contract-vector","tclk","RELEASE_NORMATIVE",()=>{if(accept.contract!==v.contractId)throw new Error("CONTRACT_ID_DIVERGENCE");return{contractId:accept.contract}}),run("tclk.identifier-field-whitelist","tclk","LOCAL_TEST",()=>{const{id,...fields}=offer,{contract,type,...core}=accept;if(normativeOfferId({...fields,transportOnly:true})!==id||normativeContractId({...offer,transportOnly:true},{...core,transportOnly:true})!==contract)throw new Error("WIDER_OBJECT_ID_DIVERGENCE");return{status:"UPSTREAM_COMPATIBILITY_WORKAROUND"};}),run("tclk.canonical-roundtrip","canonicalization","RELEASE_NORMATIVE",()=>{const line=encodeFrame(offer);if(encodeFrame(decodeFrame(line))!==line||!/^[\x20-\x7e]+$/.test(line))throw new Error("CANONICAL_DIVERGENCE");}),run("tclk.malformed-fails-closed","tclk","RELEASE_NORMATIVE",()=>{if(tryDecodeFrame('tclk1 {"type":"offer"}')!==null)throw new Error("MALFORMED_ACCEPTED");}),run("technocore.position","technocore","RELEASE_NORMATIVE",()=>{if(validatePosition("r",2,1)!=="r/2/1")throw new Error("POSITION_DIVERGENCE");mustThrow(()=>validatePosition("r",-1,1));}),run("signing.guard","signing","LOCAL_TEST",async()=>{const signer={calls:0,async sign(){this.calls++;return"signed";}};await Promise.allSettled([guardedSign({domain:"wrong",kind:"session",payload:{},canonicalPayload:"{}"},signer),guardedSign({domain:"FLOP_ROUTER_SESSION_V1",kind:"session",payload:{b:1,a:2},canonicalPayload:'{"b":1,"a":2}'},signer)]);if(signer.calls!==0)throw new Error("MALFORMED_REACHED_SIGNER");}),run("transport.rail-ref-boundary","integration","RELEASE_NORMATIVE",()=>{const r=settlementRefCompatibility("x\tunsafe");if(r.status!=="RAIL_REF_TRANSPORT_INCOMPATIBLE")throw new Error("BOUNDARY_NOT_DETECTED");return r;}),run("flop.runtime-target","flop","TARGET_SPEC",()=>({status:"TARGET_SPEC_CONFORMANCE",liveRuntime:"RUNTIME_UNAVAILABLE",failedAck:"MODELED_NOT_INGESTED_FROM_CHAIN"}))]);}
export async function routerSuite(modulePath?:string):Promise<CaseResult[]>{
 if(!modulePath)return[{id:"router.adapter",suite:"router",status:"SKIP",normativeStatus:"LOCAL_TEST",durationMs:0,details:{reason:"ROUTER_ADAPTER_NOT_CONFIGURED"}}];
 return[await run("router.cross-system","router","LOCAL_TEST",async()=>{
  const m=await import(pathToFileURL(modulePath).href),os=await import("node:os"),fs=await import("node:fs"),path=await import("node:path");
  const dir=fs.mkdtempSync(path.join(os.tmpdir(),"lab-router-"));let repo:any;
  try{const c=[{id:"disabled",identity:{},enabled:false,capabilities:[]},{id:"ok",identity:{},enabled:true,capabilities:[{modelId:"m",assurance:"SOFT"}]}];repo=new m.RouterRepository(path.join(dir,"r.db"));const router=new m.SessionRouter(new m.StaticCandidateProvider(c),repo);const d=await router.route({requestId:"lab",constraints:{modelId:"m"}});if(d.selectedMinerId!=="ok"||router.replay(d.decisionId).status!=="REPLAY_MATCH")throw new Error("ROUTER_INVARIANT_FAILURE");return{decisionId:d.decisionId};}
  finally{repo?.close();fs.rmSync(dir,{recursive:true,force:true});}
 })];
}
